# 01. Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import os

# 02. Importing Dataframe

In [2]:
# Create a string path

path = r'C:\Users\rasmu\Documents\CareerFoundry\A4 Instacart Basket Analysis\02 Data'

In [3]:
# Importing Dataframe

ords_prods_merge = pd.read_pickle(os.path.join(path, 'Prepd Data', 'orders_products_merged.pkl'))

In [4]:
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Average Orders
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Regularly busy,Regularly busy,Average Orders
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Average Orders
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Regularly busy,Average Orders
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Regularly busy,Regularly busy,Average Orders

In [5]:
ords_prods_merge.shape

(32641268, 18)

In [6]:
# Creating a subset of the dataframe

df = ords_prods_merge[:1000000]

In [7]:
df.shape

(1000000, 18)

In [8]:
df.head(10)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Average Orders
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Regularly busy,Regularly busy,Average Orders
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Average Orders
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Regularly busy,Average Orders
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Regularly busy,Regularly busy,Average Orders
5,2398795,1,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Regularly busy,Slowest days,Average Orders
6,2398795,1,2,3,7,15.0,False,10258.0,2.0,0.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Slowest days,Average Orders
7,2398795,1,2,3,7,15.0,False,12427.0,3.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Slowest days,Average Orders
8,2398795,1,2,3,7,15.0,False,13176.0,4.0,0.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Regularly busy,Slowest days,Average Orders
9,2398795,1,2,3,7,15.0,False,26088.0,5.0,1.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Slowest days,Average Orders

In [9]:
# Testing the groupby() function

df.groupby('product_name')

In [10]:
# Aggregating data w/ agg()

df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1.0              14.794925
2.0              17.085793
3.0              17.892742
4.0              17.880137
5.0              15.108513
6.0              15.352869
7.0              17.682741
8.0              16.496386
9.0              15.944846
10.0             20.104831
11.0             16.483104
12.0             15.614125
13.0             16.458631
14.0             17.523399
15.0             15.673392
16.0             18.012021
17.0             15.842139
18.0             19.349156
19.0             17.625805
20.0             17.113240
21.0             22.009038

In [11]:
# using mean() instead of agg()

df.groupby('department_id')['order_number'].mean()

department_id
1.0     14.794925
2.0     17.085793
3.0     17.892742
4.0     17.880137
5.0     15.108513
6.0     15.352869
7.0     17.682741
8.0     16.496386
9.0     15.944846
10.0    20.104831
11.0    16.483104
12.0    15.614125
13.0    16.458631
14.0    17.523399
15.0    15.673392
16.0    18.012021
17.0    15.842139
18.0    19.349156
19.0    17.625805
20.0    17.113240
21.0    22.009038
Name: order_number, dtype: float64

In [12]:
# performing multi aggregates - mean, min, max

df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1.0              14.794925   1  99
2.0              17.085793   1  98
3.0              17.892742   1  99
4.0              17.880137   1  99
5.0              15.108513   1  99
6.0              15.352869   1  99
7.0              17.682741   1  99
8.0              16.496386   1  91
9.0              15.944846   1  99
10.0             20.104831   1  99
11.0             16.483104   1  99
12.0             15.614125   1  99
13.0             16.458631   1  99
14.0             17.523399   1  99
15.0             15.673392   1  99
16.0             18.012021   1  99
17.0             15.842139   1  99
18.0             19.349156   1  99
19.0             17.625805   1  99
20.0             17.113240   1  99
21.0             22.009038   1  97

In [13]:
# performing transform() function

ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [15]:
ords_prods_merge.head(15)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Average Orders,11
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Regularly busy,Regularly busy,Average Orders,11
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Average Orders,11
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Regularly busy,Average Orders,11
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Regularly busy,Regularly busy,Average Orders,11
5,2398795,1,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Regularly busy,Slowest days,Average Orders,11
6,2398795,1,2,3,7,15.0,False,10258.0,2.0,0.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Slowest days,Average Orders,11
7,2398795,1,2,3,7,15.0,False,12427.0,3.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Slowest days,Average Orders,11
8,2398795,1,2,3,7,15.0,False,13176.0,4.0,0.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Regularly busy,Slowest days,Average Orders,11
9,2398795,1,2,3,7,15.0,False,26088.0,5.0,1.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Slowest days,Average Orders,11
10,2398795,1,2,3,7,15.0,False,13032.0,6.0,0.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Regularly busy,Slowest days,Average Orders,11
11,473747,1,3,3,12,21.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Regularly busy,Slowest days,Most Orders,11
12,473747,1,3,3,12,21.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Slowest days,Most Orders,11
13,473747,1,3,3,12,21.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Slowest days,Most Orders,11
14,473747,1,3,3,12,21.0,False,25133.0,4.0,0.0,Organic String Cheese,21.0,16.0,8.6,both,Regularly busy,Slowest days,Most Orders,11

In [16]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Average Orders,11
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Regularly busy,Regularly busy,Average Orders,11
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Average Orders,11
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Regularly busy,Average Orders,11
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Regularly busy,Regularly busy,Average Orders,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,738281,2,4,2,10,8.0,False,9681.0,12.0,0.0,Chicken Tikka Masala with Cumin Infused Basmat...,38.0,1.0,2.0,both,Regularly busy,Regularly busy,Most Orders,15
96,738281,2,4,2,10,8.0,False,21150.0,13.0,0.0,Fire Grilled Steak Bowl,38.0,1.0,5.9,both,Regularly busy,Regularly busy,Most Orders,15
97,1673511,2,5,3,11,8.0,False,47144.0,1.0,0.0,Unsweetened Original Almond Breeze Almond Milk,91.0,16.0,14.0,both,Regularly busy,Slowest days,Most Orders,15
98,1673511,2,5,3,11,8.0,False,5322.0,2.0,0.0,Gluten Free Dark Chocolate Chunk Chewy with a ...,3.0,19.0,2.9,both,Regularly busy,Slowest days,Most Orders,15
99,1673511,2,5,3,11,8.0,False,17224.0,3.0,0.0,Oats & Honey Gluten Free Granola,3.0,19.0,1.6,both,Regularly busy,Slowest days,Most Orders,15

In [17]:
pd.options.display.max_rows = None

In [18]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Average Orders,11
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Regularly busy,Regularly busy,Average Orders,11
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Average Orders,11
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Regularly busy,Average Orders,11
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Regularly busy,Regularly busy,Average Orders,11
5,2398795,1,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Regularly busy,Slowest days,Average Orders,11
6,2398795,1,2,3,7,15.0,False,10258.0,2.0,0.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Slowest days,Average Orders,11
7,2398795,1,2,3,7,15.0,False,12427.0,3.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Slowest days,Average Orders,11
8,2398795,1,2,3,7,15.0,False,13176.0,4.0,0.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Regularly busy,Slowest days,Average Orders,11
9,2398795,1,2,3,7,15.0,False,26088.0,5.0,1.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Regularly busy,Slowest days,Average Orders,11
10,2398795,1,2,3,7,15.0,False,13032.0,6.0,0.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Regularly busy,Slowest days,Average Orders,11
11,473747,1,3,3,12,21.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Regularly busy,Slowest days,Most Orders,11
12,473747,1,3,3,12,21.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Slowest days,Most Orders,11
13,473747,1,3,3,12,21.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Slowest days,Most Orders,11
14,473747,1,3,3,12,21.0,False,25133.0,4.0,0.0,Organic String Cheese,21.0,16.0,8.6,both,Regularly busy,Slowest days,Most Orders,11
15,473747,1,3,3,12,21.0,False,30450.0,5.0,0.0,Creamy Almond Butter,88.0,13.0,3.2,both,Regularly busy,Slowest days,Most Orders,11
16,2254736,1,4,4,7,29.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Least busy,Slowest days,Average Orders,11
17,2254736,1,4,4,7,29.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Least busy,Slowest days,Average Orders,11
18,2254736,1,4,4,7,29.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Least busy,Slowest days,Average Orders,11
19,2254736,1,4,4,7,29.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Least busy,Slowest days,Average Orders,11
20,2254736,1,4,4,7,29.0,False,26405.0,5.0,1.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Least busy,Slowest days,Average Orders,11
21,431534,1,5,4,15,28.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Least busy,Slowest days,Most Orders,11
22,431534,1,5,4,15,28.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Least busy,Slowest days,Most Orders,11
23,431534,1,5,4,15,28.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Least busy,Slowest days,Most Orders,11
24,431534,1,5,4,15,28.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Least busy,Slowest days,Most Orders,11
25,431534,1,5,4,15,28.0,False,10326.0,5.0,0.0,Organic Fuji Apples,24.0,4.0,2.7,both,Least busy,Slowest days,Most Orders,11
26,431534,1,5,4,15,28.0,False,17122.0,6.0,0.0,Honeycrisp Apples,24.0,4.0,14.0,both,Least busy,Slowest days,Most Orders,11
27,431534,1,5,4,15,28.0,False,41787.0,7.0,0.0,Bartlett Pears,24.0,4.0,5.0,both,Least busy,Slowest days,Most Orders,11
28,431534,1,5,4,15,28.0,False,13176.0,8.0,1.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Least busy,Slowest days,Most Orders,11
29,3367565,1,6,2,7,19.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Regularly busy,Regularly busy,Average Orders,11
30,3367565,1,6,2,7,19.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Regularly busy,Average Orders,11
31,3367565,1,6,2,7,19.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Regularly busy,Average Orders,11
32,3367565,1,6,2,7,19.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Regularly busy,Regularly busy,Average Orders,11
33,550135,1,7,1,9,20.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Regularly busy,Busiest days,Most Orders,11
34,550135,1,7,1,9,20.0,False,10258.0,2.0,1.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Busiest days,Most Orders,11
35,550135,1,7,1,9,20.0,False,12427.0,3.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Busiest days,Most Orders,11
36,550135,1,7,1,9,20.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Regularly busy,Busiest days,Most Orders,11
37,550135,1,7,1,9,20.0,False,13032.0,5.0,1.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Regularly busy,Busiest days,Most Orders,11
38,3108588,1,8,1,14,14.0,False,12427.0,1.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Busiest days,Most Orders,11
39,3108588,1,8,1,14,14.0,False,196.0,2.0,1.0,Soda,77.0,7.0,9.0,both,Regularly busy,Busiest days,Most Orders,11
40,3108588,1,8,1,14,14.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Busiest days,Most Orders,11
41,3108588,1,8,1,14,14.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Regularly busy,Busiest days,Most Orders,11
42,3108588,1,8,1,14,14.0,False,46149.0,5.0,0.0,Zero Calorie Cola,77.0,7.0,13.4,both,Regularly busy,Busiest days,Most Orders,11
43,3108588,1,8,1,14,14.0,False,49235.0,6.0,0.0,Organic Half & Half,53.0,16.0,1.8,both,Regularly busy,Busiest days,Most Orders,11
44,2295261,1,9,1,16,0.0,False,49235.0,1.0,1.0,Organic Half & Half,53.0,16.0,1.8,both,Regularly busy,Busiest days,Most Orders,11
45,2295261,1,9,1,16,0.0,False,46149.0,2.0,1.0,Zero Calorie Cola,77.0,7.0,13.4,both,Regularly busy,Busiest days,Most Orders,11
46,2295261,1,9,1,16,0.0,False,25133.0,3.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Regularly busy,Busiest days,Most Orders,11
47,2295261,1,9,1,16,0.0,False,196.0,4.0,1.0,Soda,77.0,7.0,9.0,both,Regularly busy,Busiest days,Most Orders,11
48,2295261,1,9,1,16,0.0,False,10258.0,5.0,1.0,Pistachios,117.0,19.0,3.0,both,Regularly busy,Busiest days,Most Orders,11
49,2295261,1,9,1,16,0.0,False,12427.0,6.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Regularly busy,Busiest days,Most Orders,11
50,2550362,1,10,4,8,30.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Least busy,Slowest days,Average Orders,11
51,2550362,1,10,4,8,30.0,False,46149.0,2.0,1.0,Zero Calorie Cola,77.0,7.0,13.4,both,Least busy,Slowest days,Average Orders,11
52,2550362,1,10,4,8,30.0,False,39657.0,3.0,0.0,Milk Chocolate Almonds,45.0,19.0,6.8,both,Least busy,Slowest days,Average Orders,11
53,2550362,1,10,4,8,30.0,False,38928.0,4.0,0.0,0% Greek Strained Yogurt,120.0,16.0,12.6,both,Least busy,Slowest days,Average Orders,11
54,2550362,1,10,4,8,30.0,False,25133.0,5.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Least busy,Slowest days,Average Orders,11
55,2550362,1,10,4,8,30.0,False,10258.0,6.0,1.0,Pistachios,117.0,19.0,3.0,both,Least busy,Slowest days,Average Orders,11
56,2550362,1,10,4,8,30.0,False,35951.0,7.0,0.0,Organic Unsweetened Almond Milk,91.0,16.0,1.3,both,Least busy,Slowest days,Average Orders,11
57,2550362,1,10,4,8,30.0,False,13032.0,8.0,1.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Least busy,Slowest days,Average Orders,11
58,2550362,1,10,4,8,30.0,False,12427.0,9.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Least busy,Slowest days,Average Orders,11
59,1187899,1,11,4,8,14.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Least busy,Slowest days,Average Orders,11
60,2168274,2,1,2,11,NaN,True,32792.0,1.0,0.0,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Regularly busy,Regularly busy,Most Orders,15
61,2168274,2,1,2,11,NaN,True,47766.0,2.0,0.0,Organic Avocado,24.0,4.0,6.3,both,Regularly busy,Regularly busy,Most Orders,15
62,2168274,2,1,2,11,NaN,True,20574.0,3.0,0.0,Roasted Turkey,96.0,20.0,2.3,both,Regularly busy,Regularly busy,Most Orders,15
63,2168274,2,1,2,11,NaN,True,12000.0,4.0,0.0,Baked Organic Sea Salt Crunchy Pea Snack,72.0,13.0,10.9,both,Regularly busy,Regularly busy,Most Orders,15
64,2168274,2,1,2,11,NaN,True,48110.0,5.0,0.0,Thin Stackers Brown Rice Lightly Salted,78.0,19.0,2.7,both,Regularly busy,Regularly busy,Most Orders,15
65,2168274,2,1,2,11,NaN,True,22474.0,6.0,0.0,Cheddar Bunnies Snack Crackers,78.0,19.0,4.1,both,Regularly busy,Regularly busy,Most Orders,15
66,2168274,2,1,2,11,NaN,True,16589.0,7.0,0.0,Plantain Chips,107.0,19.0,5.0,both,Regularly busy,Regularly busy,Most Orders,15
67,2168274,2,1,2,11,NaN,True,35917.0,8.0,0.0,Organic Just Concord Grape Juice,98.0,7.0,9.4,both,Regularly busy,Regularly busy,Most Orders,15
68,2168274,2,1,2,11,NaN,True,27344.0,9.0,0.0,Uncured Genoa Salami,96.0,20.0,14.8,both,Regularly busy,Regularly busy,Most Orders,15
69,2168274,2,1,2,11,NaN,True,30489.0,10.0,0.0,Original Hummus,67.0,20.0,7.5,both,Regularly busy,Regularly busy,Most Orders,15
70,2168274,2,1,2,11,NaN,True,27966.0,11.0,0.0,Organic Raspberries,123.0,4.0,4.4,both,Regularly busy,Regularly busy,Most Orders,15
71,2168274,2,1,2,11,NaN,True,13176.0,12.0,0.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Regularly busy,Regularly busy,Most Orders,15
72,2168274,2,1,2,11,NaN,True,45066.0,13.0,0.0,Honeycrisp Apple,24.0,4.0,2.5,both,Regularly busy,Regularly busy,Most Orders,15
73,1501582,2,2,5,10,10.0,False,16797.0,1.0,0.0,Strawberries,24.0,4.0,1.3,both,Regularly busy,Regularly busy,Most Orders,15
74,1501582,2,2,5,10,10.0,False,47526.0,2.0,0.0,Goat Cheese Log,21.0,16.0,2.0,both,Regularly busy,Regularly busy,Most Orders,15
75,1501582,2,2,5,10,10.0,False,8479.0,3.0,0.0,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Regularly busy,Regularly busy,Most Orders,15
76,1501582,2,2,5,10,10.0,False,47766.0,4.0,1.0,Organic Avocado,24.0,4.0,6.3,both,Regularly busy,Regularly busy,Most Orders,15
77,1501582,2,2,5,10,10.0,False,19051.0,5.0,0.0,"Pita Chips, Simply Naked, Party Size",107.0,19.0,3.9,both,Regularly busy,Regularly busy,Most Orders,15
78,1501582,2,2,5,10,10.0,False,8138.0,6.0,0.0,Traditional Hummus,67.0,20.0,2.0,both,Regularly busy,Regularly busy,Most Orders,15
79,1901567,2,3,1,10,3.0,False,47766.0,1.0,1.0,Organic Avocado,24.0,4.0,6.3,both,Regularly busy,Busiest days,Most Orders,15
80,1901567,2,3,1,10,3.0,False,32792.0,2.0,1.0,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Regularly busy,Busiest days,Most Orders,15
81,1901567,2,3,1,10,3.0,False,20574.0,3.0,1.0,Roasted Turkey,96.0,20.0,2.3,both,Regularly busy,Busiest days,Most Orders,15
82,1901567,2,3,1,10,3.0,False,7781.0,4.0,0.0,Organic Sticks Low Moisture Part Skim Mozzarel...,21.0,16.0,6.6,both,Regularly busy,Busiest days,Most Orders,15
83,1901567,2,3,1,10,3.0,False,28874.0,5.0,0.0,Carrot Ginger Soup,1.0,20.0,6.2,both,Regularly busy,Busiest days,Most Orders,15
84,738281,2,4,2,10,8.0,False,49451.0,1.0,0.0,Artichoke Spinach Dip,67.0,20.0,7.1,both,Regularly busy,Regularly busy,Most Orders,15
85,738281,2,4,2,10,8.0,False,32792.0,2.0,1.0,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Regularly busy,Regularly busy,Most Orders,15
86,738281,2,4,2,10,8.0,False,32139.0,3.0,0.0,Hommus Classic Original,67.0,20.0,7.5,both,Regularly busy,Regularly busy,Most Orders,15
87,738281,2,4,2,10,8.0,False,34688.0,4.0,0.0,Good Belly Probiotics Juice Drink Blueberry Ac...,31.0,7.0,5.8,both,Regularly busy,Regularly busy,Most Orders,15
88,738281,2,4,2,10,8.0,False,36735.0,5.0,0.0,Organic Roasted Sliced Chicken Breast,96.0,20.0,8.9,both,Regularly busy,Regularly busy,Most Orders,15
89,738281,2,4,2,10,8.0,False,37646.0,6.0,0.0,Organic Gala Apples,24.0,4.0,9.1,both,Regularly busy,Regularly busy,Most Orders,15
90,738281,2,4,2,10,8.0,False,22829.0,7.0,0.0,Multigrain Flax Seeded Flatbread Crackers,78.0,19.0,5.5,both,Regularly busy,Regularly busy,Most Orders,15
91,738281,2,4,2,10,8.0,False,24852.0,8.0,0.0,Banana,24.0,4.0,12.3,both,Regularly busy,Regularly busy,Most Orders,15
92,738281,2,4,2,10,8.0,False,47209.0,9.0,0.0,Organic Hass Avocado,24.0,4.0,4.0,both,Regularly busy,Regularly busy,Most Orders,15
93,738281,2,4,2,10,8.0,False,33276.0,10.0,0.0,Kalamata Olive Spread,67.0,20.0,10.8,both,Regularly busy,Regularly busy,Most Orders,15
94,738281,2,4,2,10,8.0,False,45613.0,11.0,0.0,Pad Thai,38.0,1.0,12.6,both,Regularly busy,Regularly busy,Most Orders,15
95,738281,2,4,2,10,8.0,False,9681.0,12.0,0.0,Chicken Tikka Masala with Cumin Infused Basmat...,38.0,1.0,2.0,both,Regularly busy,Regularly busy,Most Orders,15
96,738281,2,4,2,10,8.0,False,21150.0,13.0,0.0,Fire Grilled Steak Bowl,38.0,1.0,5.9,both,Regularly busy,Regularly busy,Most Orders,15
97,1673511,2,5,3,11,8.0,False,47144.0,1.0,0.0,Unsweetened Original Almond Breeze Almond Milk,91.0,16.0,14.0,both,Regularly busy,Slowest days,Most Orders,15
98,1673511,2,5,3,11,8.0,False,5322.0,2.0,0.0,Gluten Free Dark Chocolate Chunk Chewy with a ...,3.0,19.0,2.9,both,Regularly busy,Slowest days,Most Orders,15
99,1673511,2,5,3,11,8.0,False,17224.0,3.0,0.0,Oats & Honey Gluten Free Granola,3.0,19.0,1.6,both,Regularly busy,Slowest days,Most Orders,15

# 05. Deriving Columns w/ loc()

In [19]:
# Creating loyalty flags

ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [20]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [21]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [23]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    16381472
Loyal customer      10679578
New customer         5580218
Name: loyalty_flag, dtype: int64

In [24]:
# Checking the interpretations & flags assigned correctly

ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1  Regular customer             1
1         1  Regular customer             1
2         1  Regular customer             1
3         1  Regular customer             1
4         1  Regular customer             1
5         1  Regular customer             2
6         1  Regular customer             2
7         1  Regular customer             2
8         1  Regular customer             2
9         1  Regular customer             2
10        1  Regular customer             2
11        1  Regular customer             3
12        1  Regular customer             3
13        1  Regular customer             3
14        1  Regular customer             3
15        1  Regular customer             3
16        1  Regular customer             4
17        1  Regular customer             4
18        1  Regular customer             4
19        1  Regular customer             4
20        1  Regular customer             4
21        1  Regular customer             5
22        1  Regular customer             5
23        1  Regular customer             5
24        1  Regular customer             5
25        1  Regular customer             5
26        1  Regular customer             5
27        1  Regular customer             5
28        1  Regular customer             5
29        1  Regular customer             6
30        1  Regular customer             6
31        1  Regular customer             6
32        1  Regular customer             6
33        1  Regular customer             7
34        1  Regular customer             7
35        1  Regular customer             7
36        1  Regular customer             7
37        1  Regular customer             7
38        1  Regular customer             8
39        1  Regular customer             8
40        1  Regular customer             8
41        1  Regular customer             8
42        1  Regular customer             8
43        1  Regular customer             8
44        1  Regular customer             9
45        1  Regular customer             9
46        1  Regular customer             9
47        1  Regular customer             9
48        1  Regular customer             9
49        1  Regular customer             9
50        1  Regular customer            10
51        1  Regular customer            10
52        1  Regular customer            10
53        1  Regular customer            10
54        1  Regular customer            10
55        1  Regular customer            10
56        1  Regular customer            10
57        1  Regular customer            10
58        1  Regular customer            10
59        1  Regular customer            11